# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curlx < Formula
  desc "A keyboard-driven TUI API client with OpenAPI spec support — Postman for the terminal."
  homepage "https://github.com/kumararoosh/curlx"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.1/curlx_darwin_amd64.tar.gz"
      sha256 "249e9cb918b3312f20ef20cbc54c62ef0e711d82d950ddddfdeffac9a4fcad27"

      define_method(:install) do
        bin.install "curlx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.1/curlx_darwin_arm64.tar.gz"
      sha256 "12f430662f5a524411ff61793a3fdbafd5448d6a7e82a23e16def586a9aaf920"

      define_method(:install) do
        bin.install "curlx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.1/curlx_linux_amd64.tar.gz"
      sha256 "77b1a23e9d9628fbf64ce48a5e395ceb5784f9af2f1ca8b66127fa3b7f5bed15"
      define_method(:install) do
        bin.install "curlx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.1/curlx_linux_arm64.tar.gz"
      sha256 "c3546198d9fccd385bc2d94be9939008bafae074f6c5948761ae085490f64fe3"
      define_method(:install) do
        bin.install "curlx"
      end
    end
  end

  test do
    assert_predicate bin/"curlx", :executable?
  end
end
