# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curlx < Formula
  desc "A keyboard-driven TUI API client with OpenAPI spec support — Postman for the terminal."
  homepage "https://github.com/kumararoosh/curlx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.0/curlx_darwin_amd64.tar.gz"
      sha256 "03c56d0a0d37b4acb88b0192d8768ac43d85569dd8b17e5db94583e23dddf039"

      define_method(:install) do
        bin.install "curlx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.0/curlx_darwin_arm64.tar.gz"
      sha256 "c8963abc219309b4ade9fc5ee9079710a9d9f8112242564548c3623acfb52b48"

      define_method(:install) do
        bin.install "curlx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.0/curlx_linux_amd64.tar.gz"
      sha256 "f355da6866e95eba0bd54b3b72329944a38819a6147315cebada7f1b05b3cab1"
      define_method(:install) do
        bin.install "curlx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumararoosh/curlx/releases/download/v0.1.0/curlx_linux_arm64.tar.gz"
      sha256 "494522d21014eae6f7563004a20736205924a47c17545fec269e6712c7740abb"
      define_method(:install) do
        bin.install "curlx"
      end
    end
  end

  test do
    assert_predicate bin/"curlx", :executable?
  end
end
